---
driver:
  name: docker
  docker: /usr/local/bin/docker
  use_sudo: false

driver_config:
  privileged: true
  run_command: /sbin/init
  cap_add:
    - ALL
    - SYS_ADMIN
    - NET_ADMIN
    - NET_BIND_SERVICE
    - NET_BROADCAST
  # forward:
  #   - 9200:9200

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: node1
    driver_config:
      image: centos:7
      platform: centos
  - name: node2
    driver_config:
      image: centos:7
      platform: centos

suites:
  - name: default
    run_list:
      - recipe[elk::default]
    attributes: