---
driver:
  name: docker
  docker: /usr/local/bin/docker
  use_sudo: false
  privileged: true

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[elk::default]
    attributes:
