name 'elk'
maintainer 'Harish Shetty'
maintainer_email 'harish.kb27@gmail.com'
license 'all_rights'
description 'Installs/Configures elk'
long_description 'Installs/Configures elk'
issues_url 'https://github.com/harishkb27/cookbook-elk/issues'
source_url 'https://github.com/harishkb27/cookbook-elk'
version '0.1.0'

depends 'ark'
depends 'java'
